# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'loadMongoDB_dialog_base.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_loadMongoDBDialogBase(object):
    def setupUi(self, loadMongoDBDialogBase):
        loadMongoDBDialogBase.setObjectName(_fromUtf8("loadMongoDBDialogBase"))
        loadMongoDBDialogBase.resize(581, 489)
        self.gridLayout_2 = QtGui.QGridLayout(loadMongoDBDialogBase)
        self.gridLayout_2.setMargin(0)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.scrollArea = QtGui.QScrollArea(loadMongoDBDialogBase)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName(_fromUtf8("scrollArea"))
        self.scrollAreaWidgetContents = QtGui.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 579, 487))
        self.scrollAreaWidgetContents.setObjectName(_fromUtf8("scrollAreaWidgetContents"))
        self.gridLayout_3 = QtGui.QGridLayout(self.scrollAreaWidgetContents)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.tabWidget = QtGui.QTabWidget(self.scrollAreaWidgetContents)
        self.tabWidget.setEnabled(True)
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tab = QtGui.QWidget()
        self.tab.setObjectName(_fromUtf8("tab"))
        self.gridLayout = QtGui.QGridLayout(self.tab)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.label_5 = QtGui.QLabel(self.tab)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.gridLayout.addWidget(self.label_5, 0, 0, 1, 1)
        self.label_3 = QtGui.QLabel(self.tab)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.gridLayout.addWidget(self.label_3, 1, 0, 1, 1)
        self.label_6 = QtGui.QLabel(self.tab)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.gridLayout.addWidget(self.label_6, 2, 0, 1, 1)
        self.groupBox = QtGui.QGroupBox(self.tab)
        self.groupBox.setTitle(_fromUtf8(""))
        self.groupBox.setAlignment(QtCore.Qt.AlignCenter)
        self.groupBox.setFlat(False)
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.gridLayout_4 = QtGui.QGridLayout(self.groupBox)
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.createFile = QtGui.QPushButton(self.groupBox)
        self.createFile.setObjectName(_fromUtf8("createFile"))
        self.gridLayout_4.addWidget(self.createFile, 0, 0, 1, 1)
        self.load_collection = QtGui.QPushButton(self.groupBox)
        self.load_collection.setObjectName(_fromUtf8("load_collection"))
        self.gridLayout_4.addWidget(self.load_collection, 0, 1, 1, 1)
        self.checkBox = QtGui.QCheckBox(self.groupBox)
        self.checkBox.setText(_fromUtf8(""))
        self.checkBox.setCheckable(False)
        self.checkBox.setObjectName(_fromUtf8("checkBox"))
        self.gridLayout_4.addWidget(self.checkBox, 0, 2, 1, 1)
        self.load_field = QtGui.QComboBox(self.groupBox)
        self.load_field.setEditable(False)
        self.load_field.setObjectName(_fromUtf8("load_field"))
        self.gridLayout_4.addWidget(self.load_field, 0, 3, 1, 1)
        self.listCol = QtGui.QTreeWidget(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.listCol.sizePolicy().hasHeightForWidth())
        self.listCol.setSizePolicy(sizePolicy)
        self.listCol.setObjectName(_fromUtf8("listCol"))
        self.listCol.headerItem().setText(1, _fromUtf8("Geometry"))
        self.listCol.header().setDefaultSectionSize(210)
        self.listCol.header().setMinimumSectionSize(200)
        self.listCol.header().setStretchLastSection(False)
        self.gridLayout_4.addWidget(self.listCol, 1, 0, 1, 4)
        self.gridLayout.addWidget(self.groupBox, 3, 0, 1, 3)
        self.progressBar = QtGui.QProgressBar(self.tab)
        self.progressBar.setProperty("value", 0)
        self.progressBar.setObjectName(_fromUtf8("progressBar"))
        self.gridLayout.addWidget(self.progressBar, 4, 0, 1, 2)
        self.Close_button = QtGui.QPushButton(self.tab)
        self.Close_button.setObjectName(_fromUtf8("Close_button"))
        self.gridLayout.addWidget(self.Close_button, 4, 2, 1, 1)
        self.serverName = QtGui.QComboBox(self.tab)
        self.serverName.setEditable(True)
        self.serverName.setObjectName(_fromUtf8("serverName"))
        self.gridLayout.addWidget(self.serverName, 0, 1, 1, 2)
        self.dbName = QtGui.QComboBox(self.tab)
        self.dbName.setEditable(True)
        self.dbName.setObjectName(_fromUtf8("dbName"))
        self.gridLayout.addWidget(self.dbName, 1, 1, 1, 2)
        self.geom_field = QtGui.QComboBox(self.tab)
        self.geom_field.setEditable(True)
        self.geom_field.setObjectName(_fromUtf8("geom_field"))
        self.gridLayout.addWidget(self.geom_field, 2, 1, 1, 2)
        self.tabWidget.addTab(self.tab, _fromUtf8(""))
        self.tab_2 = QtGui.QWidget()
        self.tab_2.setObjectName(_fromUtf8("tab_2"))
        self.gridLayout_5 = QtGui.QGridLayout(self.tab_2)
        self.gridLayout_5.setObjectName(_fromUtf8("gridLayout_5"))
        self.view_all = QtGui.QListWidget(self.tab_2)
        self.view_all.setEnabled(False)
        self.view_all.setObjectName(_fromUtf8("view_all"))
        self.gridLayout_5.addWidget(self.view_all, 0, 0, 2, 2)
        self.view_button = QtGui.QPushButton(self.tab_2)
        self.view_button.setEnabled(False)
        self.view_button.setObjectName(_fromUtf8("view_button"))
        self.gridLayout_5.addWidget(self.view_button, 2, 0, 1, 1)
        self.distinct_button = QtGui.QPushButton(self.tab_2)
        self.distinct_button.setEnabled(False)
        self.distinct_button.setObjectName(_fromUtf8("distinct_button"))
        self.gridLayout_5.addWidget(self.distinct_button, 2, 1, 1, 1)
        self.set_button = QtGui.QPushButton(self.tab_2)
        self.set_button.setEnabled(False)
        self.set_button.setObjectName(_fromUtf8("set_button"))
        self.gridLayout_5.addWidget(self.set_button, 2, 2, 1, 1)
        self.view_distinct = QtGui.QListWidget(self.tab_2)
        self.view_distinct.setEnabled(False)
        self.view_distinct.setObjectName(_fromUtf8("view_distinct"))
        self.gridLayout_5.addWidget(self.view_distinct, 0, 2, 2, 1)
        self.tabWidget.addTab(self.tab_2, _fromUtf8(""))
        self.gridLayout_3.addWidget(self.tabWidget, 0, 0, 1, 1)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.gridLayout_2.addWidget(self.scrollArea, 0, 0, 1, 1)

        self.retranslateUi(loadMongoDBDialogBase)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QObject.connect(self.Close_button, QtCore.SIGNAL(_fromUtf8("clicked()")), loadMongoDBDialogBase.close)
        QtCore.QMetaObject.connectSlotsByName(loadMongoDBDialogBase)
        loadMongoDBDialogBase.setTabOrder(self.serverName, self.dbName)
        loadMongoDBDialogBase.setTabOrder(self.dbName, self.geom_field)
        loadMongoDBDialogBase.setTabOrder(self.geom_field, self.createFile)
        loadMongoDBDialogBase.setTabOrder(self.createFile, self.load_collection)
        loadMongoDBDialogBase.setTabOrder(self.load_collection, self.listCol)
        loadMongoDBDialogBase.setTabOrder(self.listCol, self.Close_button)

    def retranslateUi(self, loadMongoDBDialogBase):
        loadMongoDBDialogBase.setWindowTitle(_translate("loadMongoDBDialogBase", "Load MongoDB Points", None))
        self.label_5.setText(_translate("loadMongoDBDialogBase", "Server:", None))
        self.label_3.setText(_translate("loadMongoDBDialogBase", "Database:", None))
        self.label_6.setText(_translate("loadMongoDBDialogBase", "Geometry field:", None))
        self.createFile.setText(_translate("loadMongoDBDialogBase", "Connect", None))
        self.load_collection.setText(_translate("loadMongoDBDialogBase", "Load", None))
        self.listCol.headerItem().setText(0, _translate("loadMongoDBDialogBase", "Items", None))
        self.listCol.headerItem().setText(2, _translate("loadMongoDBDialogBase", "Count", None))
        self.Close_button.setText(_translate("loadMongoDBDialogBase", "Close", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("loadMongoDBDialogBase", "Connection", None))
        self.view_button.setText(_translate("loadMongoDBDialogBase", "View", None))
        self.distinct_button.setText(_translate("loadMongoDBDialogBase", "Distinct", None))
        self.set_button.setText(_translate("loadMongoDBDialogBase", "Set", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("loadMongoDBDialogBase", "Settings", None))

